config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :carts, only: [:destroy] do
    member do
      get 'add_to_cart', to: 'carts#add_to_cart', as: 'add_to_cart'
    end

    collection do
      get 'view_cart', to: 'carts#view_cart', as: 'view_cart'
      get 'complete_order', to: 'carts#complete_order', as: 'complete_order'
      get 'delete_order', to: 'carts#delete_order', as: 'delete_order'
    end
  end
  resources :customers
  resources :products
  resources :categories
  resources :vendors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root to: "welcome#index"
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[ show edit update destroy ]

  def index
    @customers = Customer.all
  end

  def show
  end

  def new
    @customer = Customer.new
  end

  def edit
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      redirect_to customer_url(@customer), notice: "Customer was successfully created."
    else
      render :new
    end
  end

  def update
    if @customer.update(customer_params)
      redirect_to customer_url(@customer), notice: "Customer was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @customer.destroy!
    redirect_to customers_url, notice: "Customer was successfully destroyed."
  end

  private
    def set_customer
      @customer = Customer.find(params[:id])
    end

    def customer_params
      params.require(:customer).permit(:name, :email, :password_digest)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
<div id="<%= dom_id customer %>">
  <p>
    <strong>Name:</strong>
    <%= customer.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= customer.email %>
  </p>

  <p>
    <strong>Password digest:</strong>
    <%= customer.password_digest %>
  </p>

</div>

app/views/customers/_form.html.erb
<%= form_with(model: customer) do |form| %>
  <% if customer.errors.any? %>
    <div style="color: red" class="form-group">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
        <% customer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :password_digest, style: "display: block" %>
    <%= form.password_field :password_digest, class: 'form-control'%>
  </div><br>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render "form", customer: @customer %>

<br>

<div>
  <%= link_to "Show this customer", @customer %> |
  <%= link_to "Back to customers", customers_path %>
</div>

app/views/customers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Customers</h1>

<div id="customers">
  <% @customers.each do |customer| %>
    <%= render customer %>
    <p>
      <%= link_to "Show this customer", customer %>
    </p>
  <% end %>
</div>

<%= link_to "New customer", new_customer_path %>

app/views/customers/new.html.erb
<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-md-6">
      <h1>New customer</h1>
      <%= render "form", customer: @customer %>
      <br>
      <div>
        <%= link_to "Back to customers", customers_path %>
      </div>
    </div>
  </div>
</div>

app/views/customers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @customer %>

<div>
  <%= link_to "Edit this customer", edit_customer_path(@customer) %> |
  <%= link_to "Back to customers", customers_path %>

  <%= button_to "Destroy this customer", @customer, method: :delete %>
</div>