config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :carts, only: [:destroy] do
    member do
      get 'add_to_cart', to: 'carts#add_to_cart', as: 'add_to_cart'
    end

    collection do
      get 'view_cart', to: 'carts#view_cart', as: 'view_cart'
      get 'complete_order', to: 'carts#complete_order', as: 'complete_order'
      get 'delete_order', to: 'carts#delete_order', as: 'delete_order'
    end
  end
  resources :customers
  resources :products
  resources :categories
  resources :vendors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root to: "welcome#index"
end

app/models/vendor.rb
class Vendor < ApplicationRecord
    has_many :products, dependent: :destroy
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_vendor, only: %i[ show edit update destroy ]

  def index
    @vendors = Vendor.all
  end

  def show
  end

  def new
    @vendor = Vendor.new
  end

  def edit
  end

  def create
    @vendor = Vendor.new(vendor_params)
    if @vendor.save
      redirect_to vendor_url(@vendor), notice: "Vendor was successfully created."
    else
      render :new
    end
  end

  def update
      if @vendor.update(vendor_params)
        redirect_to vendor_url(@vendor), notice: "Vendor was successfully updated."
      else
        render :edit
      end
  end

  def destroy
    @vendor.destroy!
    redirect_to vendors_url, notice: "Vendor was successfully destroyed."
  end

  private
    def set_vendor
      @vendor = Vendor.find(params[:id])
    end

    def vendor_params
      params.require(:vendor).permit(:name)
    end
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/_form.html.erb
<%= form_with(model: vendor) do |form| %>
  <% if vendor.errors.any? %>
    <div style="color: red" class="form-group">
      <h2><%= pluralize(vendor.errors.count, "error") %> prohibited this vendor from being saved:</h2>

      <ul>
        <% vendor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: 'form-control'%>
  </div><br>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/vendors/_vendor.html.erb
<div id="<%= dom_id vendor %>">
  <p>
    <strong>Name:</strong>
    <%= vendor.name %>
  </p>

</div>

app/views/vendors/edit.html.erb
<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-md-6">
      <h1>Editing vendor</h1>
      <%= render "form", vendor: @vendor %>
      <br>
      <div>
        <%= link_to "Show this vendor", @vendor %> |
        <%= link_to "Back to vendors", vendors_path %>
      </div>
    </div>
  </div>
</div>

app/views/vendors/index.html.erb
<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-md-6">
      <p style="color: green"><%= notice %></p>
      <h1>Vendors</h1>
      <%= link_to "Add new vendor", new_vendor_path, class: 'btn btn-primary' %>

      <div id="vendors"><br>
        <% @vendors.each do |vendor| %>
          <div class="card" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title"><%= vendor.name %>></h5>
              <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
              <%= link_to "Show this vendor", vendor, class: 'btn btn-primary' %>
            </div>
          </div>
          <br>
        <% end %>
      </div>
      <br>
    </div>
  </div>
</div>

app/views/vendors/new.html.erb
<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-md-6">
      <h1>New vendor</h1>
      <%= render "form", vendor: @vendor %><br>
      <div>
        <%= link_to "Back to vendors", vendors_path %>
      </div>
    </div>
  </div>
</div>

app/views/vendors/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-md-6">
      <%= render @vendor %>
      <div>
        <%= link_to "Edit this vendor", edit_vendor_path(@vendor) %> |
        <%= link_to "Back to vendors", vendors_path %><br>

        <%= button_to "Destroy this vendor", @vendor, method: :delete, class: 'btn btn-primary'%>
      </div>
    </div>
  </div>
</div>